nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/^':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600